### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by itsjusec** [dobassy/notion-hugo-exporter#15]
as soon as I set a post to Published and run the tool I get the following error message:

```Bash
/work/dist/main/notionRequest/property.js:91
script_1  |     if (prop["title"] && prop["title"].length > 1) {
script_1  |             ^
script_1  |
script_1  | TypeError: Cannot read properties of undefined (reading 'title')
script_1  |     at extractPlainText (/work/dist/main/notionRequest/property.js:91:13)
script_1  |     at pageTitle (/work/dist/main/notionRequest/property.js:7:12)
script_1  |     at /work/dist/main/notionRequest/buildFrontmatter.js:47:41
script_1  |     at Generator.next (<anonymous>)
script_1  |     at fulfilled (/work/dist/main/notionRequest/buildFrontmatter.js:5:58)
script_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
script_1  |
script_1  | Node.js v18.12.0
```

I get the error both when using Docker but also when installing the tool locally.

**Comment by itsjusec** [comment]
my default propertie was misnamed. After changing to "Name" the tool works fine for me!
